version: "3.7"
services:
  bp2023:
    build: .
    container_name: bp2023
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    networks:
      - bpnet
    restart: always
  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - bpnet
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=ednevnik
      - MYSQL_USER=ednevnik
      - MYSQL_PASSWORD=csdigital
      - MYSQL_ROOT_PASSWORD=csdigital
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - bpnet
volumes:
  mysql:
networks:
  bpnet:
    driver: bridge